### ISSUE TITLE
Feathers generate fails on node 7.5.0

### ISSUE THREAD

**Issue by morrislaptop** [feathersjs/feathers-cli#64] opened 2017-02-13 11:26 UTC
### Steps to reproduce

* Install feathers-cli globally
* Run `feathers generate`

### Expected behavior

Feathers sample app generated. 

### Actual behavior

Got this:

```
> feathers generate
local@craigs-mm-imac~$

? Project name (feathers-chat)

events.js:161
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at constructor.Base.prompt (/Users/craigmorris/.config/yarn/global/node_modules/generator-feathers/node_modules/yeoman-generator/lib/base.js:240:45)
    at constructor.prompting (/Users/craigmorris/.config/yarn/global/node_modules/generator-feathers/generators/app/index.js:195:10)
    at Object.<anonymous> (/Users/craigmorris/.config/yarn/global/node_modules/generator-feathers/node_modules/yeoman-generator/lib/base.js:439:23)
    at /Users/craigmorris/.config/yarn/global/node_modules/generator-feathers/node_modules/run-async/index.js:25:25
    at /Users/craigmorris/.config/yarn/global/node_modules/generator-feathers/node_modules/run-async/index.js:24:19
    at /Users/craigmorris/.config/yarn/global/node_modules/generator-feathers/node_modules/yeoman-generator/lib/base.js:440:9
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
feathers-cli 1.2.7

**NodeJS version**:
7.5.0

**Operating System**:
Mac Sierra

**Comment by daffl** [comment] 2017-02-15 06:41
I can't reproduce this. Are you using nvm? Also, try `npm cache clean` and reinstalling `feathers-cli` you might also have an old global version of `yo`.

**Comment by daffl** [comment] 2017-02-18 03:14
Closing since we don't have more info and I can't reproduce.

**Closed by daffl** 2017-02-18 03:14 UTC

**Comment by mzalazar** [comment] 2017-08-07 19:23
Same problem here:
/bin/sh: 1: yarn: not found
Ubuntu 16

**Comment by mzalazar** [comment] 2017-08-07 19:27
I solve it by doing:
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn

REFERENCE: https://yarnpkg.com/lang/en/docs/install/#linux-tab
