### ISSUE TITLE
Can not generate services with Node 8.1.0

### ISSUE THREAD

**Issue by blackmatch** [feathersjs/feathers-cli#94] opened 2017-06-12 11:58 UTC
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
I want to generate an authentication, so I run `feathers generate authentication`. But it stop here
<img width="937" alt="2017-06-12 19 53 36" src="https://user-images.githubusercontent.com/12443954/27032843-4ca17ace-4fa9-11e7-8f1b-a2fa60266cb1.png">
I can do nothing. press any key is not working.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: 8.1.0

**Operating System**: macOS

**Browser Version**: 

**React Native Version**:

**Module Loader**:

**Comment by nihaf** [comment] 2017-06-12 15:18
Can reproduce the problem with:
- Windows 10 Pro 64bit
- Node 8.1.0
- Latest feathers-cli

Tried on Windows Cmd, PowerShell, babun (zsh). Each with and without administrative rights.

**Comment by daffl** [comment] 2017-06-12 17:19
@eddyystop Can you reproduce this on your Windows machine?

**Comment by eddyystop** [comment] 2017-06-12 18:23
I run a Ubuntu VM. I'll set up a Windows environment tomorrow.

**Comment by daffl** [comment] 2017-06-12 20:21
I can also confirm that this is also happening on Node 8.1.0 on Mac OS.

**Comment by daffl** [comment] 2017-06-13 23:14
This was caused by an issue in Node 8.1.0 (https://github.com/nodejs/node/issues/13557). I just verified that it has been fixed in the latest version.

If you are encountering this problem, please upgrade to 8.1.1 or later.

**Closed by daffl** 2017-06-13 23:14 UTC
