### ISSUE TITLE
Can not create service on postgres if default.json already has the connection string

### ISSUE THREAD

**Issue by ramosquito5** [feathersjs/feathers-cli#100] opened 2017-06-29 02:10 UTC
https://stackoverflow.com/questions/44814788/how-to-create-feathersjs-services-with-knex-postgres/44815184#44815184

### Steps to reproduce

While trying out FeathersJS, i tried to create two services following the docs. The first is called x and the other y.

When I create x with

```
~/r/feathers-chat ❯❯❯ feathers generate service
? What kind of service is it? KnexJS
? What is the name of the service? x
? Which path should the service be registered on? /x
? Which database are you connecting to? PostgreSQL
? What is the database connection string?
  postgres://user:password@localhost:5432/feathers_chat
```
Everything works perfectly.

When I create y

```
~/r/feathers-chat ❯❯❯ feathers generate service
? What kind of service is it? KnexJS
? What is the name of the service? y
? Which path should the service be registered on? /y
? Which database are you connecting to? PostgreSQL
```
The following error is thrown.

```
events.js:160
  throw er; // Unhandled 'error' event
  ^

TypeError: Parameter "url" must be a string, not object
at Url.parse (url.js:88:11)
at Object.urlParse [as parse] (url.js:82:5)
at ConnectionGenerator._getConfiguration (/Users/user/.nvm/versions/node/v6.10.2/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/connection/index.js:46:24)
at ConnectionGenerator._writeConfiguration (/Users/user/.nvm/versions/node/v6.10.2/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/connection/index.js:103:32)
at ConnectionGenerator.writing (/Users/user/.nvm/versions/node/v6.10.2/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/connection/index.js:293:10)
at Object.<anonymous> (/Users/user/.nvm/versions/node/v6.10.2/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/index.js:417:23)
at /Users/user/.nvm/versions/node/v6.10.2/lib/node_modules/feathers-cli/node_modules/run-async/index.js:25:25
at /Users/user/.nvm/versions/node/v6.10.2/lib/node_modules/feathers-cli/node_modules/run-async/index.js:24:19
at /Users/user/.nvm/versions/node/v6.10.2/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/index.js:418:9
at runCallback (timers.js:666:20)
```
It seems that the feathersJS client crashes when there a postgres connection defined in the default.js

So if i create the connection before hand, the client crashes upon creating the first service with the same exact error.

I uninstalled feathers-cli@2.2.2 and installed version 2.1.1 and I had no more problems.

### System configuration
**Module versions** (especially the part that's not working):
 feathers-cli@2.2.2
**NodeJS version**:
v6.10.2
**Operating System**:
MAC OS  10.12.4

**Comment by daffl** [comment] 2017-06-29 04:42
So it worked in a previous version? I think this regression might be caused by https://github.com/feathersjs/generator-feathers/pull/229

**Comment by ramosquito5** [comment] 2017-06-29 16:11
Yes, it worked just fine in the previous version. l will give it a look

**Comment by jdziat** [comment] 2017-07-01 21:43
I just submitted a PR that should resolve the issue.

**Comment by daffl** [comment] 2017-07-02 19:58
Closed via #240, thank you @jdziat!

**Closed by daffl** 2017-07-02 19:58 UTC

**Comment by alzab** [comment] 2017-09-09 08:09
I'm seeing this issue while using cli v2.3.5 - could I be missing something? Again, reverting to 2.1.1 solves it for me.

**Comment by daffl** [comment] 2017-09-10 01:51
@alzab Can you create a new issue with the steps to reproduce to keep track of this?

**Comment by alzab** [comment] 2017-09-10 02:43
@daffl sure thing - https://github.com/feathersjs/generator-feathers/issues/274 - in my case I was using a custom connection object
